### ISSUE TITLE
ginit fails

### ISSUE THREAD

**Issue by bigerl** [pkumod/gStore#100]
## Problem

`bin/ginit -make` crashes with a segfault

## Reproduce
To reproduce the issue, run the attached [Dockerfile.txt](https://github.com/pkumod/gStore/files/5980905/Dockerfile.txt) with 

```
docker build -f Dockerfile.txt .
```

The relevant part of the log where ginit crashes is:
```
Step 12/15 : RUN bin/ginit -make
 ---> Running in 860f178ec51d
the current settings are as below: 
key : value
------------------------------------------------------------
BackupTime : 2000       # 4 am (GMT+8)
buffer_maxium : 100
db_home : .
db_suffix : .db
debug_level : simple
gstore_mode : single
operation_logs : true
thread_maxium : 1000

begin encode RDF from : /gStore/data/system/system.nt ...
finish initial sub2id_pre2id_obj2id
begin build Prefix new.
_error_log:./system.db/parse_error.log
RDFParser parseFile done!
_error_log:./system.db/parse_error.log
RDFParser parseFile done!
Add triples to Trie to prepare for BuildPrefix
BuildPrefix done. used1
finish rdfparser0

after info in sub2id_
finish rdfparser4

after info in sub2id_
Segmentation fault (core dumped)
```

## Reason
 I do not really know. But I assume it is related to missing synchronization in multi-threading because the command works when compiled with debug options. 

## Workaround
Change `CFLAG` and `EXEFLAG` in the makefile to the following:
```
CFLAGS = -c -Wall -pthread -std=c++11 -g
EXEFLAG = -pthread -g -std=c++11
```

**Comment by bigerl** [comment]
The authors suggested in an email conversation a change in the dockerfile resulting in this dockerfile:
```
FROM ubuntu:groovy
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get -qq update && \
    apt-get -qq install -y make cmake uuid-dev git openjdk-11-jdk gcc g++ pkg-config wget

# packages requried by gStore
RUN apt-get -qq install -y libreadline-dev curl libcurl4 libcurl4-openssl-dev
RUN apt-get -qq install -y libboost-all-dev

WORKDIR /
RUN git clone --branch 0.9 https://github.com/pkumod/gStore.git

WORKDIR /gStore
RUN git checkout c3b117140566dc1dfb3c0a771a7967641940addc

RUN make pre
RUN make -j
# downlad swdf dataset
RUN wget -qO- https://hobbitdata.informatik.uni-leipzig.de/ISWC2020_Tentris/swdf.zip | gunzip > swdf.nt
# load swdf dataset
RUN bin/gbuild "swdf" "swdf.nt" 2>&1
# run http endpoint
RUN bin/ghttp "swdf"
```

This results in a segfault again. Here the end of the log:
```
...
Compilation ends successfully!
scripts/init.sh: line 6:   471 Segmentation fault      (core dumped) "bin/ginit" "-make" &> /dev/null
make: *** [makefile:125: all] Error 139
Error response from daemon: The command '/bin/sh -c make -j' returned a non-zero code: 2
```

The reason is again ginit. The logging snipped above is produced by this part of the makefile:
https://github.com/pkumod/gStore/blob/c3b117140566dc1dfb3c0a771a7967641940addc/makefile#L123-L125
which calls this script
https://github.com/pkumod/gStore/blob/c3b117140566dc1dfb3c0a771a7967641940addc/scripts/init.sh#L6 

So it does basically the same as 
```
RUN bin/ginit -make
``` 
from the first dockerfile.

**Comment by bookug** [comment]
We have built a community, please ask questions there:
http://www.gstore.cn/pcsite/index.html#/medical

**Comment by fyulingi** [comment]
Could you please give us some information about your system settings?
In our test, some particular versions of tools used in bin/gbuild may cause error. So I highly recommend user prepare your settings according to our docs.

Ps: I also encountered the same "Segmentation fault" when bin/gbuild almost done, it is on a ubuntu20.04 machine with gcc/g++ 9.3.0, so I downgraded my gcc/g++ to 7.5.0(because I also tried on ubuntu18.04 with gcc/g++ 7.5.0, and it successed), and the error was fixed.

**Comment by bigerl** [comment]
ubuntu:groovy is Ubuntu 20.10 which comes with gcc/g++ 10.2. 

I updated the Dockerfile to use ubuntu:bionic/20.04 instead which comes with g++ 7.5.0 as you mentioned. 

The updated `Dockerfile` looks now like:
```
FROM ubuntu:bionic
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get -qq update && \
    apt-get -qq install -y make cmake uuid-dev git openjdk-11-jdk gcc g++ pkg-config wget

# packages required by gStore
RUN apt-get -qq install -y libreadline-dev curl libcurl4 libcurl4-openssl-dev lsof libboost-all-dev

WORKDIR /
RUN git clone --branch 0.9 https://github.com/pkumod/gStore.git

WORKDIR /gStore
# use a specific commit of gStore
RUN git checkout 389528bb5665bdd8bd943ff3e09ab51b8138584f

# build gStore
RUN make pre
RUN make -j

# downlad swdf dataset
RUN wget -qO- https://hobbitdata.informatik.uni-leipzig.de/ISWC2020_Tentris/swdf.zip | gunzip > swdf.nt

# load SWDF dataset
RUN bin/gbuild "swdf" "swdf.nt"
# run SWDF http endpoint
CMD ["/gStore/bin/ghttp", "swdf"]
# endpoint is exposed at port 9000. You should forward this port from the docker container
```

On the [latest commit](https://github.com/pkumod/gStore/commit/389528bb5665bdd8bd943ff3e09ab51b8138584f), building, loading and querying seems to work now. I tried a simple query which retrieves the whole graph (`SELECT * WHERE { ?s ?p ?o}`) which ran successfully:
```
url -X GET "http://localhost:9000/?db_name=swdf&query=SELECT+%2A+WHERE+%7B+%3Fs++%3Fp++%3Fo+%7D"
```
So I guess g++ 7.5.0 is a hard requirement, then?

**Comment by fyulingi** [comment]
We have done some tests on ginit with g++9.3, and found this bug is caused by a bool function in Kvstore.cpp has no return. May "-O2" option in higher version of g++ is more strict on this. Now we have fixed this bug in new commit. 
Thanks for your issue, and if you have any other questions, please feel free to ask here.
