### ISSUE TITLE
SPARQL 有完整的支持文档么？

### ISSUE THREAD

**Issue by coooodeXjl** [pkumod/gStore#101]
查看了 gstore 开发者文档给出的 SPARQL 示例，感觉和 w3c 的 SPARQL 标准语法有一定出入，请问 gstore 有完整，正式的 SPARQL 语言查询文档嘛？

**Comment by zouleipku** [comment]
***@***.*** 代表 ***@***.***>:

 

查看了给出的 SPARQL 示例，感觉和 w3c 的 SPARQL 标准语法有一定出入，请问 gstore 有完整，正式的 SPARQL 语言文档嘛？

**Comment by bookug** [comment]
We have built a community, please ask questions there:
http://www.gstore.cn/pcsite/index.html#/medical
