### ISSUE TITLE
在Ubuntu上ginit失败的问题

### ISSUE THREAD

**Issue by LebronXuh** [pkumod/gStore#102]
gStore在Ubuntu最后编译的时候（即执行bin/ginit）时候会出现ru'xi如下图错误
![image](https://user-images.githubusercontent.com/32254172/116957293-1cb61b80-acca-11eb-823e-efa117e8656a.png)

并且make完成之后，会缺少很多文件，如下图
![image](https://user-images.githubusercontent.com/32254172/116957318-33f50900-acca-11eb-88b4-12f126e9f632.png)

我按照官方文档可以进行了官方示例的增删查，但gshow、gmonitor等命令无法执行，报错如下
![image](https://user-images.githubusercontent.com/32254172/116957484-88988400-acca-11eb-932a-a84bd3721d32.png)

 #跟[#100](https://github.com/pkumod/gStore/issues/100)出现问题相似，请问一下有什么解决方法吗？
谢谢！

**Comment by bookug** [comment]
We have built a community, please ask questions there:
http://www.gstore.cn/pcsite/index.html#/medical
