### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by xqx1568** [pkumod/gStore#103]
g++ -O2 -pthread -std=c++11 -o bin/shutdown .objs/shutdown.o .objs/KVstore.o .objs/SITree.o .objs/SIStorage.o .objs/SINode.o .objs/SIIntlNode.o .objs/SILeafNode.o .objs/SIHeap.o  .objs/ISTree.o .objs/ISStorage.o .objs/ISNode.o .objs/ISIntlNode.o .objs/ISLeafNode.o .objs/ISHeap.o  .objs/IVTree.o .objs/IVStorage.o .objs/IVNode.o .objs/IVIntlNode.o .objs/IVLeafNode.o .objs/IVHeap.o  .objs/IVArray.o .objs/IVEntry.o .objs/IVBlockManager.o .objs/ISArray.o .objs/ISEntry.o .objs/ISBlockManager.o  .objs/VSTree.o .objs/EntryBuffer.o .objs/LRUCache.o .objs/VNode.o .objs/StringIndex.o .objs/RDFParser.o .objs/SparqlParser.o .objs/DBparser.o .objs/SparqlLexer.o .objs/TurtleParser.o .objs/QueryParser.o .objs/Operation.o .objs/Server.o .objs/Client.o .objs/Socket.o  .objs/Database.o .objs/Join.o .objs/Strategy.o .objs/Util.o .objs/Bstr.o .objs/Stream.o .objs/Triple.o .objs/BloomFilter.o .objs/VList.o .objs/SigEntry.o .objs/Signature.o .objs/SPARQLquery.o .objs/BasicQuery.o .objs/ResultSet.o  .objs/IDList.o .objs/Varset.o .objs/QueryTree.o .objs/TempResult.o .objs/QueryCache.o .objs/GeneralEvaluation.o .objs/Trie.o .objs/TrieNode.o -fopenmp -march=native -L./api/http/cpp/lib -lclient -lreadline -L./lib -L/usr/local/lib -lantlr -lgcov -lboost_thread -lboost_filesystem -lboost_system -lboost_regex -lpthread -I/usr/local/include/boost -lcurl
/usr/bin/ld: ./api/http/cpp/lib/libclient.a(client.o): relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIC
.objs/shutdown.o: In function `main':
shutdown.cpp:(.text.startup+0x18b): undefined reference to `CHttpClient::Get(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
/usr/bin/ld: final link failed: Symbol needs debug section which does not exist
collect2: error: ld returned 1 exit status
makefile:133: recipe for target 'bin/shutdown' failed
make: *** [bin/shutdown] Error 1

I don't know what cause this problem.
My dependency packages are as follows：
glibc 2.27
gcc 7.5.0
g++ 7.5.0
boost 1.65.1
make
readline
openjdk
libcurl 
I would be most grateful if you could offer me some help.

**Comment by bookug** [comment]
We have built a community, please ask questions there:
http://www.gstore.cn/pcsite/index.html#/medical
