### ISSUE TITLE
About triples file

### ISSUE THREAD

**Issue by xqx1568** [pkumod/gStore#105]
sorry, I can't post question in your community, I loss my password and when I try to change password I got "请求异常".
If I want to store knoledge base like DBpedia-16-10 or Freebase, what is the details of triple file.
Should I process entities and relationships without prefixes like the triples.txt you provided?
My gStore is serviced for Ganswer.

**Comment by nicklin96** [comment]
Hello xqx1568！
Yes, your own triple file should be the same as the triple.txt we provided, prefix not needed.

**Comment by xqx1568** [comment]
Thank you for your help! Closed.
