### ISSUE TITLE
支持的数据量级及效率

### ISSUE THREAD

**Issue by Invincibled** [pkumod/gStore#110]
您好，我想请教一下，gStore，能够支持的数据量级别，，能支持到TB及么？
如果到TB级别，效率如何，有测试过么？

期待您的回复，谢谢.

**Comment by YuqqiZhou** [comment]
您好！gStore目前支持的数据量级别为50亿条边，在LUBM数据集下，50亿条边的文件大概占用672GB。如果1TB的文件里面存储的边数没有超过50亿，是可以支持的。我们没有针对TB级别的数据专门进行过测试，谢谢您对gStore的关注！

**Comment by Invincibled** [comment]
感谢您的回复.

**Comment by PKU-ICST-DB** [comment]
感谢您的回复.
