### ISSUE TITLE
Bug in single-quoted strings

### ISSUE THREAD

**Issue by gzz2000** [pkumod/gStore#125]
SPARQL supports both single-quoted and double-quoted string literals (see [here](https://www.w3.org/TR/sparql11-query/#:~:text=The%20general%20syntax%20for%20literals%20is%20a%20string%20(enclosed%20in%20either%20double%20quotes%2C%20%22...%22%2C%20or%20single%20quotes%2C%20%27...%27)%2C%20with%20either%20an%20optional%20language%20tag%20(introduced%20by%20%40)%20or%20an%20optional%20datatype%20IRI%20or%20prefixed%20name%20(introduced%20by%20%5E%5E).)). 

However, if single-quoted string is inserted into the current gstore database, it will not trigger an error during insertion but will fail to be read out during a subsequent query.

```sparql
INSERT DATA { <test:test> <test:is> 'abc' }
SELECT ?val WHERE { <test:test> <test:is> ?val }
```

The query (using ghttp) will return a JSON like this:
```json
{"error": {"errorMsg:": "the information is not complete!"}}
```

The reason lies in the parsing logic [here](https://github.com/pkumod/gStore/blob/fa083e7cd957b9cb24642e2788cf4c99528108d9/Query/ResultSet.cpp#L314). It ignores the possibility of single quotes.

**Comment by zxlchina** [comment]
您的邮件我已收到，谢谢~~~

**Comment by Jeevan620** [comment]
Thanks for your feedback.
We have temporarily fixed this bug.

**Comment by zxlchina** [comment]
您的邮件我已收到，谢谢~~~

**Comment by WenJieLiHnu** [comment]
<p>111</p>
