### ISSUE TITLE
查询提示文件为空

### ISSUE THREAD

**Issue by xiaoli-user** [pkumod/gStore#134]
我按照文档快速入门的教程，再数据库查询阶段出现问题。
<img width="586" alt="屏幕截图 2023-12-31 095100" src="https://github.com/pkumod/gStore/assets/80106358/935787b3-1616-4125-b631-d0fc0cf5e224">
然后我尝试查看数据库状态，没有发现问题：
<img width="625" alt="屏幕截图 2023-12-31 095208" src="https://github.com/pkumod/gStore/assets/80106358/7c8de445-5202-4fdb-9676-4e114b5f88e6">
请问这是什么原因？

**Comment by lsvih** [comment]
你好，请给出您查询的具体命令；从图一的报错看，应该是您没有指定查询文件的路径，正确的查询命令一般会类似于`./bin/gquery -db lubm -q ./data/lubm/lubm_q2.sql`

**Comment by xiaoli-user** [comment]
我查询的命令是bin/gquery -db lubm -f ./data/lubm/lubm_q0.sql，整个操作是在docker环境下的，另外我发现在之前的步骤中(/bin/ginit -db lubm)会出现log4cplus:ERROR No appenders could be found for logger (root)这样的错误信息，不过最后会提示init成功，所以我没有在意这个报错，对后面的步骤会有影响吗？

**Comment by xiaoli-user** [comment]
> 你好，请给出您查询的具体命令；从图一的报错看，应该是您没有指定查询文件的路径，正确的查询命令一般会类似于`./bin/gquery -db lubm -q ./data/lubm/lubm_q2.sql`

我把 -f 改成 -q 之后正常了，查到了和教程中相同的结果。但原教程中写的是 -f，是不是笔误？

**Comment by lsvih** [comment]
收到，文档的示例确实有误，感谢您帮忙定位该问题，我们会尽快更新文档！@WenJieLiHnu @jeevan-wang 


ginit 的问题会在您对应的 issue #135 中处理
