### ISSUE TITLE
ginit出现error提示

### ISSUE THREAD

**Issue by xiaoli-user** [pkumod/gStore#135]
我使用docker的方式使用gstore，然后在初始化时提示Error，后续查询也不能正常进行
<img width="494" alt="屏幕截图 2023-12-31 181704" src="https://github.com/pkumod/gStore/assets/80106358/f40dce61-9dc2-4108-b814-b3c4929998d7">

**Comment by lsvih** [comment]
您好，暂时未能复现这个问题，请问您使用的是哪个 docker 包呀？

**Comment by xiaoli-user** [comment]
您好，我是使用命令拉取的最新的包，docker pull pkumodlab/gstore-docker:latest
我目前还不是很理解init的作用，因此连续输入了两次相同的命令，出现这个bug，但我不知道它会不会对后面的使用造成影响，因为我提这个问题时，查询的命令没有写正确（把-q写成了-f），虽然有这个报错，但后面也查到了对应的结果。两次报错的信息如下：
<img width="735" alt="屏幕截图 2023-12-31 195528" src="https://github.com/pkumod/gStore/assets/80106358/42ee298a-32b7-49d4-82d7-03fc4a206ae6">
<img width="690" alt="屏幕截图 2023-12-31 195549" src="https://github.com/pkumod/gStore/assets/80106358/acd26b3a-244c-431c-bfcf-e1b6c6f1cea2">

**Comment by lsvih** [comment]
第一个是汇报error日志写入的路径；第二个是docker里log4cplus环境的问题，不会影响使用~


ginit一般是用来初始化一个新库用，一般直接使用gbuild来从nt文件建立新库就行
