### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by gsscsd** [pkumod/gStore#36]
![2018-09-29 15-00-41](https://user-images.githubusercontent.com/12953213/46244857-fea02480-c417-11e8-8df0-1b0382d441f3.png)

### 本地链接库缺失

**Comment by bookug** [comment]
you need to install libcurl-dev

**Comment by gsscsd** [comment]
Thank you very much .The problem ,has been solved.

发送自 Windows 10 版邮件应用

发件人: Li, Zeng
发送时间: 2018年9月29日 21:03
收件人: pkumod/gStore
抄送: JCWang; Author
主题: Re: [pkumod/gStore] 编译错误 (#36)

you need to install libcurl-dev
