### ISSUE TITLE
make failed

### ISSUE THREAD

**Issue by flame110** [pkumod/gStore#41]
![image](https://user-images.githubusercontent.com/31184925/48469491-03833100-e82a-11e8-9e0b-f263b29492db.png)
安装的时候出现如图所示错误，所有依赖已安装。是不是系统默认的boost版本的问题？

**Comment by bookug** [comment]
no, the problem here is not caused by libboost. It is the hpp file that is not found by the compiler.
You should make sure that the boost has been installed properly and you can find the header file in sysytem. Maybe you can try the setup scripts we provide in scripts/setup/

**Comment by flame110** [comment]
THX! problem sloved afer the boost was reinstalled.
