### ISSUE TITLE
make error “ clang: error: unsupported option '-fopenmp' ”

### ISSUE THREAD

**Issue by HagridThick** [pkumod/gStore#42]
➜  gStore git:(master) make
g++ -c -Wall -O2 -pthread -std=c++11 Main/gbuild.cpp -I./tools/libantlr3c-3.4/ -I./tools/libantlr3c-3.4/include -o .objs/gbuild.o -fopenmp -march=native
clang: error: unsupported option '-fopenmp'
make: *** [.objs/gbuild.o] Error 1

➜  gStore git:(master) which gcc
/usr/bin/gcc
➜  gStore git:(master) gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by bookug** [comment]
We do not test with Clang and Mac, so you had better search on Internet and find the solution specially for Mac:)
