### ISSUE TITLE
No add/sub in APIs

### ISSUE THREAD

**Issue by zeabin** [pkumod/gStore#47]
我正在基于gStore做一个课程实验，需要用到增删数据库中部分数据的功能，但是在API中没有找到对应的函数，只能考虑调用`gadd`、`gsub`命令实现，以后会增加这两个API吗？

**Comment by summercyy** [comment]
同学你好，增删数据可以通过 api 中的 query 函数实现，只要在 sparql 中写相应的 INSERT / DELETE 就可以了，相关 sparql 语法规则可以参考 https://www.w3.org/TR/2013/REC-sparql11-update-20130321/#insertData

**Comment by zeabin** [comment]
原来是这样，感谢回复
