### ISSUE TITLE
Server stopped abnormally, restarting server

### ISSUE THREAD

**Issue by ljch2018** [pkumod/gStore#58]
20190522 09:21:34       Wait for input...
20190522 09:21:34       Server stopped abnormally, restarting server...
20190522 09:21:34       cannot bind to port 3307. @Server::createConnection
20190522 09:21:34       Failed to create connection at port 3307.
请问怎么解决，多谢多谢。

**Comment by WenJieLiHnu** [comment]
请问你这个是在什么场景下发生的，版本是最新版本吗？是在启动ghttp还是什么？
