### ISSUE TITLE
pkubase怎么调用

### ISSUE THREAD

**Issue by sudazzk** [pkumod/gStore#59]
import sys
sys.path.append('../gStore-master/api/http/python/src')
import GstoreConnector

IP = "http://pkubase.gstore-pku.com"
Port = 80
username = "endpoint"
password = "123"
sparql = """
select ?x where { <澳大利亚> <道路通行> ?z.?x <道路通行> ?z}
"""

# start a gc with given IP, Port, username and password
gc =  GstoreConnector.GstoreConnector(IP, Port, username, password)

# query
res = gc.query("pkubase", "json", sparql)
print(res)

**Comment by Redbudjing** [comment]
您好，这样调用是正确的，请问您具体是遇到了什么问题吗？

**Comment by sudazzk** [comment]
谢谢。知道问题出在哪了，我代码执行前，没有编译源代码，得到可执行文件。
哎，只能在linux系统下编译调用，有什么办法可以在windows系统上安装使用吗？

**Comment by Redbudjing** [comment]
您好，本系统只提供Linux安装版本的。windows上可以考虑用虚拟机。
