### ISSUE TITLE
编码问题

### ISSUE THREAD

**Issue by sudazzk** [pkumod/gStore#60]
1 # -*- coding: UTF-8 -*-
  2
  3 import sys
  4 sys.path.append('/home/z50002826/gStore-master/api/http/python/src')
  5 import GstoreConnector
  6
  8 ## 需要在linux下编译得到可执行文件，才可调用
  9 """
 10 cd gStore/
 11 sudo ./scripts/setup/setup_ubuntu.sh
 12 sudo make pre
 13 make -j4
 14 """
 15
 16 IP = "pkubase.gstore-pku.com"
 17 Port = 80
 18 username = "endpoint"
 19 password = "123"
 34
 35 sparql = "select ?x where { <莫妮卡·贝鲁奇> <代表作品> ?x. }"

 39 gc =  GstoreConnector.GstoreConnector(IP, Port, username, password)
 42 res = gc.query("pkubase", "json", sparql, 'GET')
 50 print(res)

api 调用的结果  和  网页http://pkubase.gstore-pku.com/上面 运行的结果不一样，编码有问题？

**Comment by suxunbin** [comment]
Thanks for your issue. The Chinese encoding between Python2 and Python3 are incompatible. We have fixed the bug. You can use either Python2 or Python3 now.
