### ISSUE TITLE
docker image pull access denied

### ISSUE THREAD

**Issue by Kiran-38** [pkumod/gStore#61]
Error response from daemon: pull access denied for pkmud/gstore, repository does not exist or may require 'docker login'

**Comment by suxunbin** [comment]
emmm，you need to pull from pkumod/gstore

**Comment by suxunbin** [comment]
You can read DOCKER_DEPLOY_EN.md under docs/ for help.

**Comment by Kiran-38** [comment]
docker build -t gstore
"docker build" requires exactly 1 argument.
See 'docker build --help'.

Usage:  docker build [OPTIONS] PATH | URL | -

Build an image from a Dockerfile
