### ISSUE TITLE
run make but got one Error

### ISSUE THREAD

**Issue by YueCongPKU** [pkumod/gStore#62]
$ sudo ./scripts/setup/setup_$(ARCH).sh
  $ make pre
  $ make
when I follow these steps and run make under gStore root, I got one error:
g++ -O2 -pthread -std=c++11 -o bin/gbuild .objs/gbuild.o .objs/KVstore.o .objs/SITree.o .objs/SIStorage.o .objs/SINode.o .objs/SIIntlNode.o .objs/SILeafNode.o .objs/SIHeap.o  .objs/ISTree.o .objs/ISStorage.o .objs/ISNode.o .objs/ISIntlNode.o .objs/ISLeafNode.o .objs/ISHeap.o  .objs/IVTree.o .objs/IVStorage.o .objs/IVNode.o .objs/IVIntlNode.o .objs/IVLeafNode.o .objs/IVHeap.o  .objs/IVArray.o .objs/IVEntry.o .objs/IVBlockManager.o .objs/ISArray.o .objs/ISEntry.o .objs/ISBlockManager.o  .objs/VSTree.o .objs/EntryBuffer.o .objs/LRUCache.o .objs/VNode.o .objs/StringIndex.o .objs/RDFParser.o .objs/SparqlParser.o .objs/DBparser.o .objs/SparqlLexer.o .objs/TurtleParser.o .objs/QueryParser.o .objs/Operation.o .objs/Server.o .objs/Client.o .objs/Socket.o  .objs/Database.o .objs/Join.o .objs/Strategy.o .objs/Util.o .objs/Bstr.o .objs/Stream.o .objs/Triple.o .objs/BloomFilter.o .objs/VList.o .objs/SigEntry.o .objs/Signature.o .objs/SPARQLquery.o .objs/BasicQuery.o .objs/ResultSet.o  .objs/IDList.o .objs/Varset.o .objs/QueryTree.o .objs/TempResult.o .objs/QueryCache.o .objs/GeneralEvaluation.o .objs/Trie.o .objs/TrieNode.o -lreadline -L./lib -L/usr/local/lib -lantlr -lgcov -lboost_thread -lboost_filesystem -lboost_system -lboost_regex -lpthread -I/usr/local/include/boost -lcurl -fopenmp -march=native
/usr/bin/ld: cannot find -lcurl
collect2: error: ld returned 1 exit status
make: *** [bin/gbuild] Error 1

did I miss something?

**Comment by bookug** [comment]
You need to install curl development library, e.g., on CentOS it is libcurl-devel.
