### ISSUE TITLE
gStore是否支持增删改功能？

### ISSUE THREAD

**Issue by JunWangSir** [pkumod/gStore#65]
用Dockor部署了gStore，通过Java调用接口（gStore文件内提供的GstoreConnector.java内的方法）这个GstoreConnector.java里面只有查询和用户相关的一些接口，没有找到增删改功能。

我怎么才能实现对gStore数据的增删改呢？

**Comment by suxunbin** [comment]
支持，使用query接口，sparql语句用delete和insert的语法即可
