### ISSUE TITLE
essay 链接似乎失效了

### ISSUE THREAD

**Issue by choleraehyq** [pkumod/gStore#70]
https://github.com/pkumod/gStore/blob/master/docs/ESSAY.md 这个链接里面的 http://www.icst.pku.edu.cn/intro/leizou/projects/papers/demo.pdf 这个链接，我打开之后是 Not Found

**Comment by bookug** [comment]
@summercyy

**Comment by summercyy** [comment]
链接已更新
https://jszx6.pku.edu.cn/pub/sjglsys/docs/20190909213425677387.pdf
