### ISSUE TITLE
dockefile is incomplete to build from bare machine

### ISSUE THREAD

**Issue by yzs981130** [pkumod/gStore#75]
the origin dockerfile needs user run `make pre` on the host, according to the [directions on docker build from source](https://github.com/pkumod/gStore/blame/master/docs/DOCKER_DEPLOY_CN.md#L19), which violates the docker's principle.
it's better to do all the dirty job inside build container and reduce the image size if possible.
the base image should also be uniformed for global use.

**Comment by bookug** [comment]
@suxunbin
