### ISSUE TITLE
make error with client.h and GstoreConnector.h

### ISSUE THREAD

**Issue by GTMalogic** [pkumod/gStore#76]
there is something wrong with shuadown.cpp,when the client.h is quoted  instead of  GstoreConnector.h,the terminator says no defination for ‘GstoreConnector::Get(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)’
and 
GstoreConnector::GstoreConnector()
if the client.h and  GstoreConnector.h are both quoted, it says redefination for GstoreConnector, what should I do?

**Comment by bookug** [comment]
@suxunbin

**Comment by bookug** [comment]
We have built a community, please ask questions there:
http://www.gstore.cn/pcsite/index.html#/medical
