### ISSUE TITLE
query data by python

### ISSUE THREAD

**Issue by OKtang** [pkumod/gStore#80]
Hi,
Can I get the data from the kg published on ccks2019 by the http request now and can I build a connector by GstoreConnector("dbpedia.gstore-pku.com", 80, "endpoint", "123") . Thank you for your reply.

**Comment by Redbudjing** [comment]
Yes, of course. You can query the KG of ccks2019 by building a connector:  GstoreConnector("pkubase.gstore-pku.com", 80, "endpoint", "123") and the KG for dbpedia is also available on "dbpedia.gstore-pku.com"

**Comment by OKtang** [comment]
Thanks, and if I should query in 'dbpedia_full' or other database?

**Comment by OKtang** [comment]
When I query in 'pkubase', I get an error of 404.

**Comment by Redbudjing** [comment]
the database name for url "pkubase.gstore-pku.com" is "pkubase".
while the database name for url "dbpedia.gstore-pku.com" is "dbpedia_full"
you should query in corrsponding format to either of these databases.
