### ISSUE TITLE
查询结果不一致

### ISSUE THREAD

**Issue by OKtang** [pkumod/gStore#83]
你好，
对于某些实体，通过Python代码查询的时候，返回结果为0条，但是在网页端复制sparql语句进行查询，是有结果的，请问可能是什么原因导致了这一问题呢？

**Comment by OKtang** [comment]
pkubase

**Comment by hjfan-wkz** [comment]
可否给出查询示例和截图信息，谢谢～

**Comment by bookug** [comment]
We have built a community, please ask questions there:
http://www.gstore.cn/pcsite/index.html#/medical
