### ISSUE TITLE
gStore在centos上编译提示如下错误，请问如何解决，多谢。

### ISSUE THREAD

**Issue by gaoruiqing1983** [pkumod/gStore#85]
错误信息：
cal/include/boost -lcurl -fopenmp -march=native
/usr/local/lib/libreadline.so：对‘tgetnum’未定义的引用
/usr/local/lib/libreadline.so：对‘tgetent’未定义的引用
/usr/local/lib/libreadline.so：对‘tgetstr’未定义的引用
/usr/local/lib/libreadline.so：对‘tgoto’未定义的引用
/usr/local/lib/libreadline.so：对‘UP’未定义的引用
/usr/local/lib/libreadline.so：对‘BC’未定义的引用
/usr/local/lib/libreadline.so：对‘tputs’未定义的引用
/usr/local/lib/libreadline.so：对‘PC’未定义的引用
/usr/local/lib/libreadline.so：对‘tgetflag’未定义的引用
collect2: 错误：ld 返回 1
make: *** [bin/gexport] 错误 1

环境上readline已经升级到最新版本：
ls -l /usr/local/lib/ | grep libreadline
-rw-r--r--.  1 root root 1458626 4月   3 03:29 libreadline.a
-rw-r--r--.  1 root root 1458626 4月   3 03:28 libreadline.old
lrwxrwxrwx.  1 root root      16 4月   3 03:29 libreadline.so -> libreadline.so.8
lrwxrwxrwx.  1 root root      18 4月   3 03:29 libreadline.so.8 -> libreadline.so.8.0
-rwxr-xr-x.  1 root root  841872 4月   3 03:29 libreadline.so.8.0
-rwxr-xr-x.  1 root root  841872 4月   3 03:28 libreadline.so.8.0.old

补充说明：ncurses也是最新版本了：
find / -name ncurses
/openkg/ncurses-6.2/test/ncurses
/openkg/ncurses-6.2/ncurses
/home/huawei/env/anaconda3/include/ncurses
/home/huawei/env/anaconda3/pkgs/ncurses-6.1-he6710b0_1/include/ncurses

**Comment by bookug** [comment]
需要安装devel版本，比如readline-devel
